const DEFAULT_ACHIEVEMENT_BADGE_ASSET_BASE_URL = "/images/achievements";

export const ACHIEVEMENT_BADGE_ASSET_BASE_URL =
  process.env.NEXT_PUBLIC_ACHIEVEMENT_BADGE_ASSET_BASE_URL?.trim() || DEFAULT_ACHIEVEMENT_BADGE_ASSET_BASE_URL;
